export const CUSTOM_CURSOR_STATES = {
    DISABLED: 'DISABLED',
    OPEN_PROJECT: 'OPEN_PROJECT',
    CLOSE_PROJECT: 'CLOSE_PROJECT',
    SHOW_INFO: 'SHOW_INFO',
    NEXT_PROJECT: 'NEXT_PROJECT',
    PREV_PROJECT: 'PREV_PROJECT',
    CLOSE_DESCRIPTION: 'CLOSE_DESCRIPTION'
}

export const CAROUSEL_NAV_SCREEN_PCT = 20